// Generated by https://quicktype.io

export interface Character {
    id: string;
    name: string;
    creator: Publisher;
    title: string;
    class: string;
    skills: string;
    alt_img?: string;
}

export enum Publisher {
    Independent = "Independent",
}
